### PR TITLE
add user description

### LINKED ISSUE #70: user description

### PR DESCRIPTION
**Pull request by Dee-bugg**

### CODE REVIEW

**Review by erikgalajda — CHANGES_REQUESTED** [review]
@Dee-bugg could you please remove prettier format from this PR? It's really hard to read what was implemented. We need to format with prettier in a separate PR.

**Comment by Dee-bugg** [comment]
> 

yeah ill try to do that in a bit i completely forgot i had it auto reformatting things

**Comment by erikgalajda** [comment]
ok, if it's too complicated to reverse that i will format the whole project with prettier, merge to develop so we will eventually see only the changes related to the user description task if our prettier setup is identical.

**Review by erikgalajda — CHANGES_REQUESTED** [review]
The description is missing in the user modal (after clicking show more there should be the full user description).
User should be able to add description in their profile page.
I think we should not include description input in the registration form, your opinion?

**Comment by Dee-bugg** [comment]
> The description is missing in the user modal (after clicking show more there should be the full user description). User should be able to add description in their profile page. I think we should not include description input in the registration form, your opinion?

added it in the modal and the profile page
and i agree with you that we shouldn't add it to the registration form in order to keep registration quick and simple

**Review by erikgalajda — APPROVED** [review]
I added some missing stuff and refactored a bit. Please have a look and let me know your opinion. I also cleared the git commit history.

**Pull request merged**
